### ISSUE TITLE
Getting 'undeclared identifier' on DrawIcon

### ISSUE THREAD

**Issue by adamski** [danlin/danlin_modules#1]
I've added the module to my JUCE project, but when I call `DrawIcon` from a `paint` method I get 

```
Use of undeclared identifier 'DrawIcon'
```

**Comment by danlin** [comment]
Sorry im changed the API. Documentation Update coming soon.

Try this in paint:
<code>
FontAwesome.drawAt(g, FontAwesome.getIcon(FontAwesome_Music, 24, Colours::yellow), 10, 10)
</code>

FontAwesome.drawAt: Draw the Icon to a Graphic Context
FontAwesome.getIcon: Get Icon from the Icon Cache

**Comment by adamski** [comment]
Great thanks, I'll check this out later.
