### ISSUE TITLE
Reflect version in juce_module_info

### ISSUE THREAD

**Issue by adamski** [danlin/danlin_modules#3]
Version in juce_module_info is 4.2, FontAwesome version is 4.3.

Also suggest adding your own versioning separately to the FontAwesome version, to show updates/improvements not to do with FontAwesome (such as the bug fix :))

**Comment by danlin** [comment]
:+1: you get this :)

**Comment by danlin** [comment]
here we go new version string is 1.0-4.3.0

first part is my module release version
second part is FontAwesome version
