### ISSUE TITLE
DrawIcon not exists

### ISSUE THREAD

**Issue by memetea** [danlin/danlin_modules#4]
hi:
the DrawIcon function does not exist.  Is the example usage in README  not correct?

**Comment by danlin** [comment]
jep sorry the readme is outdated

**Comment by danlin** [comment]
See FontAwesome.h inside the module folder

use this functions to draw the icons
`
    static void drawAt(juce::Graphics &g, Icon icon, float size, juce::Colour colour, int x, int y, float scaleFactor);
    static void drawCenterd(juce::Graphics &g, Icon icon, float size, juce::Colour colour, juce::Rectangle<int> r, float scaleFactor);
    
    static void drawAt(juce::Graphics &g, Icon icon, float size, juce::Colour colour, int x, int y);
    static void drawCenterd(juce::Graphics &g, Icon icon, float size, juce::Colour colour, juce::Rectangle<int> r);
    
    static void drawAtRotated(juce::Graphics &g, Icon icon, float size, juce::Colour colour, int x, int y, float rotation, float scaleFactor);
    static void drawCenterdRotated(juce::Graphics &g, Icon icon, float size, juce::Colour colour, juce::Rectangle<int> r, float rotation, float scaleFactor);

    static void drawAtRotated(juce::Graphics &g, Icon icon, float size, juce::Colour colour, int x, int y, float rotation);
    static void drawCenterdRotated(juce::Graphics &g, Icon icon, float size, juce::Colour colour, juce::Rectangle<int> r, float rotation);
`

`
void paint (Graphics& g) override {
	FontAwesome::drawAt(g, FontAwesome_Play, 24, Colours::black, 10, 10);
}
`
